### ISSUE TITLE
PPM correction.

### ISSUE THREAD

**Issue by hexameron** [PiInTheSky/lora-gateway#1]
Could you add a simple test to output a carrier on 434.leo so that the modules can be checked against a Ham Radio and a PPM offset could be put back into the Gateway ? That would help at the narrower bandwidths where the drift is much less than the initial offset.

**Comment by daveake** [comment]
Will do.  There's going to be an autotune option (read error --> update PPM) and I'll do it then.  I have some other changes to finish first so it'll be after those.

**Comment by hexameron** [comment]
Just using AutoTune would keep the code a lot cleaner. I will try that.
