### ISSUE TITLE
To include Listener frequency

### ISSUE THREAD

**Issue by g8dhe** [PiInTheSky/lora-gateway#15]
To add the Listener frequency for each port in the "listener_telemetry" and/or"listener_information" fields.  This would allow identification of the freq. in use by payloads that are not well documented / announced in advance via the IRC robot functions.

**Comment by Romeo-Golf** [comment]
Seems reasonable :)

**Comment by PiInTheSky** [comment]
Done now - see latest (V1.8.15)
