### ISSUE TITLE
Michrochip RN2483 Compatibility

### ISSUE THREAD

**Issue by suspirik** [PiInTheSky/lora-gateway#16]
Hi all,
 
I am working on LoRa RN 2483 -raspberry pi c 2011 gateway and I have to set server ip and ports. But on the instructions of semtech network server gateway settings, there are files such as sys_config or global_config but I do not have them on raspberry so I download packet forwarder to get that files. But on the cooking-hacks site where I have instructions for raspberry site, they do not have such instructions and no mention about packet forwarder nor lora gateway application. Do you have any suggestion? Can I use this code for  michrochip RN 2483 also? 

I have arduPi lib and LoRaWAN lib so far.And will try to connect OTAA join.
 
Thanks in advance...

**Comment by daveake** [comment]
This is not a LoRaWAN gateway, just a LoRa gateway.  It's intended for use
in tracking balloons and cannot be used for LoRaWAN applications.
