### ISSUE TITLE
lowopt_ settings

### ISSUE THREAD

**Issue by g8dhe** [PiInTheSky/lora-gateway#25]
Doesn't appear to function any Y/N/0/1 makes no difference.

**Comment by dbrooke** [comment]
Assuming that the problem is that it can't be disabled if a mode setting has already enabled it then I suspect this may be https://github.com/PiInTheSky/lora-gateway/pull/11 which is probably work in progress as the request has been closed but the changes have not yet appeared in the master branch

**Comment by daveake** [comment]
I'll check this later.  Might have got lost in the merge.

**Comment by daveake** [comment]
Turns out it wasn't fixed; my bad.

Fixed in V1.8.2 which is up down; V1.8.3 coming later today.
