### ISSUE TITLE
Enabling SSDV

### ISSUE THREAD

**Issue by hyde00001** [PiInTheSky/lora-gateway#29]
The Github README.md doesn't mention installing SSDV to store images locally while the UKHAS wiki https://ukhas.org.uk/guides:lora_tracking_guide?s[]=lora does. It would probably help fools like me to update the Github instructions... Many thanks for all the effort you put into this.

**Comment by PiInTheSky** [comment]
Added.  SSDV is now apt-gettable on Pi so I've changed the instructions accordingly.
