### ISSUE TITLE
ambiguous variables

### ISSUE THREAD

**Issue by Romeo-Golf** [PiInTheSky/lora-gateway#33]
Can you confirm the permitted values for the following variables which have =0 in the gateway-example.txt

implicit_0=0
lowopt_0=0

But show Y/N answers in the README.md

Implicit_<n>=<Y/N>.  e.g. Implicit_0=Y
lowopt_<n>=<Y/N>.  Enables or disables low data rate optimization.

Thanks

**Comment by daveake** [comment]
Y=1  N=0

**Comment by Romeo-Golf** [comment]
Thanks for clarifying :)

Does the code accept both, or should the documentation and gateway-sample.txt indicate these should be specified in 0/1 format?

**Comment by PiInTheSky** [comment]
Any of 1, Y, y, t or T will be accepted to enable a setting; anything else disables it.
