### ISSUE TITLE
No telnet service?

### ISSUE THREAD

**Issue by xpix** [PiInTheSky/lora-gateway#38]
Hello, i watched ur YouTube video but in code i can't find the HAP Port. Was this an experimental Feature, will this merged with the main code?

https://www.youtube.com/watch?v=zq7Abui3Lds

**Comment by daveake** [comment]
It's separate.  I have a separate build that includes anything not fully
tested, and anything that I don't want to release publically.

**Comment by PiInTheSky** [comment]
Now included, with configuration description in README.
