### ISSUE TITLE
New Feature: Additional metadata logging

### ISSUE THREAD

**Issue by g8dhe** [PiInTheSky/lora-gateway#5]
Would it be possible to expand the logging info. possibly using an additional config. parameter say;
TelemetryMetadata=[Y/N]
The data to consist of modem config., recieve metadata and raw telemetry.
Channel, Frequency, Imp/Exp, Bandwidth, SF, EC, LDRO on/off, Recieve time, AFC, RSSI, SNR, "raw data"
e.g.
0,434.2950MHz,Explicit,20.8k,SF8,EC4:6,LDRO,201508031408,-0.3Khz,-100,20,"Telemetry"

This would then allow much easier understanding of the performance of a given link after the event.

**Comment by daveake** [comment]
Yup, good idea.

**Comment by g8dhe** [comment]
OK well I've had ago myself!  You should find the input on the Pull request if I have got the hang of GIT right!

**Comment by PiInTheSky** [comment]
Done now, by Phil Crump - see latest (V1.8.15)
