### ISSUE TITLE
MaxAFCStep may be used uninitialised

### ISSUE THREAD

**Issue by ED6E0F17** [PiInTheSky/lora-gateway#56]
I may be missing something, but If I don`t set MaxAFCstep in config, I am not going to be able to use calling mode to correct drifty payloads.

**Comment by PiInTheSky** [comment]
If you don't set a value, it will be zero, which disables its action.  So AFC works but isn't bounded.

**Comment by daveake** [comment]
Yeah, that's reasonable.  I'll add to the list.

Dave

**Comment by ED6E0F17** [comment]
My actual problem was a typo in gateway.txt: "AFC0=Y", so if you could make AFC default to on, that would be good too.......

**Comment by dbrooke** [comment]
AFC is only needed at the narrower bandwidth settings so it doesn't necessarily make sense to default to on.

Also you can easily toggle the setting using the f or F key.
