### ISSUE TITLE
Get parity error of Hamming decoding

### ISSUE THREAD

**Issue by kelleann** [PiInTheSky/lora-gateway#64]
Did you know how to get parity error result when Hamming(6,4) or Hamming(5,4)? In your implementation, you don't implement to report parity error result  to the user when Hamming(6,4) or Hamming(5,4). So in the commodity LoRa nodes, is there a way to get the parity error when Hamming(6,4) or Hamming(5,4)? I look forward to hearing from you. Thanks a lot.

**Comment by daveake** [comment]
No.
