### ISSUE TITLE
LoRa Gatewau needs UKHAS CRC checks 

### ISSUE THREAD

**Issue by zanco** [PiInTheSky/lora-gateway#76]
As allready done in Hab Base. the LoRa Gateway would be better of with UKHAS CRC checks too

Thanks,

Ben
![image](https://github.com/PiInTheSky/lora-gateway/assets/4477734/c1ff7957-a095-4829-ba54-70ec4c23ba55)

**Comment by PiInTheSky** [comment]
Added in V1.10.2 along with some other changes to make the parsing/upload of UKHAS sentences to Sondehub more robust.
